version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: crypto-trading-db
    environment:
      POSTGRES_DB: crypto-trading-sim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # change for prod deployment
      POSTGRES_ROOT_PASSWORD: postgres # change for prod deployment
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crypto-trading-sim"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    container_name: crypto-trading-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
